### ISSUE TITLE
Drop array-find and object.assign from dependencies

### ISSUE THREAD

**Issue by takenspc** [azu/analyze-desumasu-dearu#14]
It seems that the primary usage of this library is implementing textlint plugins which are running on node.js. For now, textlint requires node.js 6+.

Node 6+ implements Array.prototype.find and Object.assign so that array-find and object.assign are not necessary.

If you don't mind I will submit a pull request to drop them.

If I missed anything, please let me know ☺️.

**Comment by azu** [comment]
Welcome to Pull Request!
