### ISSUE TITLE
接続的な "である" を無視するオプション

### ISSUE THREAD

**Issue by azu** [azu/analyze-desumasu-dearu#5]
> 今日はいい天気である場合に明日はどうなるか

のような"である"を無視するオプション。
実質的に末尾の"である。"だけに絞るようなオプションが必要かどうか?

常体(である調)の定義が結構曖昧であるから、この文がそうなのかも分からないというのが問題です。

- [「です・ます」調と「だ・である」調の使い方 | 美しい言葉](http://kazahanamirai.com/gobi.html)
- [論文の書き方◆である調](http://hac.cside.com/bunsho/1shou/47setu.html)
- [常体(ジョウタイ)とは - コトバンク](https://kotobank.jp/word/%E5%B8%B8%E4%BD%93-532447)
- [あははっ　敬語　常体と敬体](http://www3.kcn.ne.jp/~jarry/keig/c01c07.htm)

**Comment by matsu-chara** [comment]
+1
ちょうど今日２０〜箇所くらい”である”を修正したのですが、接続的な "である" の場合適切な言い換えがすぐ思い付かないケースが多く、接続的な "である" を無視するオプションがあると嬉しいと思いました。（日本語文法的な視点からの意見ではないですが・・）

**Comment by azu** [comment]
オプションで追加しました。ライブラリのデフォルトは同じままです。
https://github.com/azu/textlint-rule-no-mix-dearu-desumasu のルールの方はデフォルトを緩くしたい(false positiveにしない)ので、このオプションをデフォルト有効にする予定です

**Comment by azu** [comment]
ルール側も対応しました [Release 3.0.0 · azu/textlint-rule-no-mix-dearu-desumasu](https://github.com/azu/textlint-rule-no-mix-dearu-desumasu/releases/tag/3.0.0 "Release 3.0.0 · azu/textlint-rule-no-mix-dearu-desumasu")
